apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybottest
  labels:
    app: polybottest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybottest
  template:
    metadata:
      labels:
        app: polybottest
    spec:
      containers:
      - name: server
        image: loaykewan/my_poly_pot_k8s_project_prod:v1.0.20
        ports:
        - containerPort: 8443 # Ensure this matches your application's listening port
        env:
          - name: secret_name
            value: loaytokensecret-for-amz-prolect
          - name: TELEGRAM_APP_URL
            value: https://loayk-k8s-new1.int-devops.click
          - name: region_of_sqs
            value: eu-west-3
        volumeMounts:
          - name: my-tls-volume
            mountPath: /usr/src/app/tls  # The directory where the certificate will be available
      volumes:
        - name: my-tls-volume
          secret:
            secretName: my-tls-secret
            items:
              - key: tls.crt
                path: cert  # It will be available in the container as /usr/src/app/tls/cert
              - key: tls.key
                path: key   # It will be available in the container as /usr/src/app/tls/key
---
apiVersion: v1
kind: Service
metadata:
  name: polybottest-service
spec:
  selector:
    app: polybottest
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
