apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybottest
  labels:
    app: polybottest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybottest
  template:
    metadata:
        labels:
          app: polybottest
    spec:
      containers:
      - name: server
        image: loaykewan/my_poly_pot_k8s_project_prod:v1.0.5
        ports:
        - containerPort: 8443 # Ensure this matches your application's listening port
        env:
          - name: secret_name
            value: loaytokensecret-for-amz-prolect
          - name: TELEGRAM_APP_URL
            value: https://loayk-k8s-new1.int-devops.click
          - name: region_of_sqs
            value: eu-west-3
          - name: my_cert
            valueFrom:
              secretKeyRef:
                name: my-tls-secret
                key: cert
---
apiVersion: v1
kind: Service
metadata:
  name: polybottest-service
spec:
  selector:
    app: polybottest
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443